# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    target-branch: "2.x"
    schedule:
      interval: "monthly"
    groups:
      symfony:
        patterns:
          - "symfony/*"
      twig:
        patterns:
          - "twig/*"
      phpstan:
        dependency-type: development
        patterns:
          - "phpstan/*"
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "2.x"
    schedule:
      interval: "monthly"
    groups:
      babel:
        patterns:
          - "@babel/*"
      eslint:
        patterns:
          - "@typescript-eslint/*"
          - "eslint*"
      webpack:
        patterns:
          - "webpack*"
  - package-ecosystem: "docker"
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: "monthly"
    target-branch: "2.x"
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: "monthly"
    target-branch: "2.x"
