# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false
    handle_all_throwables: true
    # see https://symfony.com/doc/current/deployment/proxies.html
    trusted_proxies: '%env(TRUSTED_PROXIES)%'

    http_client:
        default_options:
            retry_failed:
                enabled: true
        scoped_clients:
            osmcha.client:
                base_uri: '%osmcha.api.url%'
                headers:
                    Accept: 'application/json'
                    Authorization: '%osmcha.api.key%'
            osm.client:
                base_uri: '%osm.api.url%'
                headers:
                    Accept: 'application/json'
                    'User-Agent': '%app.userAgent%'

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
