files:
  - source: "/translations/messages.en.xlf"
    translation: "/translations/messages.%locale%.xlf"
    languages_mapping:
      locale:
        ar: "ar"
        bg: "bg"
        de: "de"
        es-ES: "es_ES"
        fr: "fr"
        hu: "hu"
        it: "it"
        ja: "ja"
        ko: "ko"
        nl: "nl"
        pl: "pl"
        pt-PT: "pt_PT"
        pt-BR: "pt_BR"
        sl: "sl"
        sq: "sq"
        uk: "uk"
        zh-CN: "zh_CN"
        zh-TW: "zh_TW"
  - source: "/translations/security.en.xlf"
    translation: "/translations/security.%locale%.xlf"
    languages_mapping:
      locale:
        ar: "ar"
        bg: "bg"
        de: "de"
        es-ES: "es_ES"
        fr: "fr"
        hu: "hu"
        it: "it"
        ja: "ja"
        ko: "ko"
        nl: "nl"
        pl: "pl"
        pt-PT: "pt_PT"
        pt-BR: "pt_BR"
        sl: "sl"
        sq: "sq"
        uk: "uk"
        zh-CN: "zh_CN"
        zh-TW: "zh_TW"
  - source: "/translations/time.en.xlf"
    translation: "/translations/time.%locale%.xlf"
    languages_mapping:
      locale:
        ar: "ar"
        bg: "bg"
        de: "de"
        es-ES: "es_ES"
        fr: "fr"
        hu: "hu"
        it: "it"
        ja: "ja"
        ko: "ko"
        nl: "nl"
        pl: "pl"
        pt-PT: "pt_PT"
        pt-BR: "pt_BR"
        sl: "sl"
        sq: "sq"
        uk: "uk"
        zh-CN: "zh_CN"
        zh-TW: "zh_TW"
  - source: "/translations/time+intl-icu.en.xlf"
    translation: "/translations/time+intl-icu.%locale%.xlf"
    languages_mapping:
      locale:
        ar: "ar"
        bg: "bg"
        de: "de"
        es-ES: "es_ES"
        fr: "fr"
        hu: "hu"
        it: "it"
        ja: "ja"
        ko: "ko"
        nl: "nl"
        pl: "pl"
        pt-PT: "pt_PT"
        pt-BR: "pt_BR"
        sl: "sl"
        sq: "sq"
        uk: "uk"
        zh-CN: "zh_CN"
        zh-TW: "zh_TW"
  - source: "/translations/validators.en.xlf"
    translation: "/translations/validators.%locale%.xlf"
    languages_mapping:
      locale:
        ar: "ar"
        bg: "bg"
        de: "de"
        es-ES: "es_ES"
        fr: "fr"
        hu: "hu"
        it: "it"
        ja: "ja"
        ko: "ko"
        nl: "nl"
        pl: "pl"
        pt-PT: "pt_PT"
        pt-BR: "pt_BR"
        sl: "sl"
        sq: "sq"
        uk: "uk"
        zh-CN: "zh_CN"
        zh-TW: "zh_TW"
