files:
  - source: "/translations/*.en.xlf"
    translation: "/translations/%original_file_name%-%locale%.xlf"
    languages_mapping:
      locale:
        es-ES: "es_ES"
        pt-PT: "pt_PT"
        pt-BR: "pt_BR"
        zh-CN: "zh_CN"
        zh-TW: "zh_TW"
