name: app

type: php:8.3

relationships:
    database: "database:postgresql"

runtime:
    extensions:
        - apcu
        - mbstring
        - sodium
        - ctype
        - iconv
        - intl
        - pdo_pgsql
        - sodium

variables:
   php:
       opcache.preload: config/preload.php

build:
    flavor: none

disk: 512

web:
    locations:
        "/":
            root: "public"
            expires: 1h
            passthru: "/index.php"

mounts:
    "/var": { source: local, source_path: var }

hooks:
    build: |
        set -x -e

        curl -fs https://get.symfony.com/cloud/configurator | bash

        NODE_VERSION=18 symfony-build
    deploy: |
        set -x -e

        symfony-deploy

crons:
    clean-delete-users:
        spec: '0 0 * * *'
        commands:
            start: php bin/console osm:deleted-users
    update-africa-drc:
        spec: '0 1 * * *'
        commands:
            start: php bin/console osmcha:new-mapper drc
    update-africa-ghana:
        spec: '0 1 * * *'
        commands:
            start: php bin/console osmcha:new-mapper ghana
    update-africa-liberia:
        spec: '0 1 * * *'
        commands:
            start: php bin/console osmcha:new-mapper liberia
    update-africa-libya:
        spec: '0 23 * * *'
        commands:
            start: php bin/console osmcha:new-mapper libya
    update-africa-niger:
        spec: '0 1 * * *'
        commands:
            start: php bin/console osmcha:new-mapper niger
    update-africa-nigeria:
        spec: '0 1 * * *'
        commands:
            start: php bin/console osmcha:new-mapper nigeria
    update-africa-tanzania:
        spec: '0 22 * * *'
        commands:
            start: php bin/console osmcha:new-mapper tanzania
    update-africa-togo:
        spec: '0 1 * * *'
        commands:
            start: php bin/console osmcha:new-mapper togo
    update-africa-uganda:
        spec: '0 22 * * *'
        commands:
            start: php bin/console osmcha:new-mapper uganda
    update-asia-bangladesh:
        spec: '0 19 * * *'
        commands:
            start: php bin/console osmcha:new-mapper bangladesh
    update-asia-cambodia:
        spec: '0 18 * * *'
        commands:
            start: php bin/console osmcha:new-mapper cambodia
    update-asia-china-beijing:
        spec: '0 17 * * *'
        commands:
            start: php bin/console osmcha:new-mapper china-beijing
    update-asia-china-heilongjiang:
        spec: '0 17 * * *'
        commands:
            start: php bin/console osmcha:new-mapper china-heilongjiang
    update-asia-china-hunan:
        spec: '0 17 * * *'
        commands:
            start: php bin/console osmcha:new-mapper china-hunan
    update-asia-china:
        spec: '0 17 * * *'
        commands:
            start: php bin/console osmcha:new-mapper china
    update-asia-east-timor:
        spec: '0 16 * * *'
        commands:
            start: php bin/console osmcha:new-mapper east-timor
    update-asia-hongkong:
        spec: '0 17 * * *'
        commands:
            start: php bin/console osmcha:new-mapper hongkong
    update-asia-india:
        spec: '30 19 * * *'
        commands:
            start: php bin/console osmcha:new-mapper india
    update-asia-indonesia:
        spec: '0 17 * * *'
        commands:
            start: php bin/console osmcha:new-mapper indonesia
    update-asia-iraq:
        spec: '0 20 * * *'
        commands:
            start: php bin/console osmcha:new-mapper iraq
    update-asia-japan:
        spec: '0 16 * * *'
        commands:
            start: php bin/console osmcha:new-mapper japan
    update-asia-laos:
        spec: '0 18 * * *'
        commands:
            start: php bin/console osmcha:new-mapper laos
    update-asia-macao:
        spec: '0 17 * * *'
        commands:
            start: php bin/console osmcha:new-mapper macao
    update-asia-myanmar:
        spec: '30 18 * * *'
        commands:
            start: php bin/console osmcha:new-mapper myanmar
    update-asia-north-korea:
        spec: '0 16 * * *'
        commands:
            start: php bin/console osmcha:new-mapper north-korea
    update-asia-pakistan:
        spec: '0 20 * * *'
        commands:
            start: php bin/console osmcha:new-mapper pakistan
    update-asia-papua-new-guinea:
        spec: '0 15 * * *'
        commands:
            start: php bin/console osmcha:new-mapper papua-new-guinea
    update-asia-philippines:
        spec: '0 17 * * *'
        commands:
            start: php bin/console osmcha:new-mapper philippines
    update-asia-south-korea:
        spec: '0 16 * * *'
        commands:
            start: php bin/console osmcha:new-mapper south-korea
    update-asia-taiwan:
        spec: '0 17 * * *'
        commands:
            start: php bin/console osmcha:new-mapper taiwan
    update-asia-thailand:
        spec: '0 18 * * *'
        commands:
            start: php bin/console osmcha:new-mapper thailand
    update-asia-turkey:
        spec: '0 22 * * *'
        commands:
            start: php bin/console osmcha:new-mapper turkey
    update-asia-vietnam:
        spec: '0 18 * * *'
        commands:
            start: php bin/console osmcha:new-mapper vietnam
    update-australia-australia:
        spec: '30 15 * * *'
        commands:
            start: php bin/console osmcha:new-mapper australia
    update-europe-albania:
        spec: '0 1 * * *'
        commands:
            start: php bin/console osmcha:new-mapper albania
    update-europe-austria:
        spec: '0 1 * * *'
        commands:
            start: php bin/console osmcha:new-mapper austria
    update-europe-basque-country-south-landes:
        spec: '0 1 * * *'
        commands:
            start: php bin/console osmcha:new-mapper basque-country-south-landes
    update-europe-belgium:
        spec: '0 1 * * *'
        commands:
            start: php bin/console osmcha:new-mapper belgium
    update-europe-bulgaria:
        spec: '0 1 * * *'
        commands:
            start: php bin/console osmcha:new-mapper bulgaria
    update-europe-catalan_countries:
        spec: '0 1 * * *'
        commands:
            start: php bin/console osmcha:new-mapper catalan_countries
    update-europe-dachli-obersee-rheintal:
        spec: '0 1 * * *'
        commands:
            start: php bin/console osmcha:new-mapper dachli-obersee-rheintal
    update-europe-france:
        spec: '0 1 * * *'
        commands:
            start: php bin/console osmcha:new-mapper france
    update-europe-germany-berlin-neukoelln:
        spec: '0 1 * * *'
        commands:
            start: php bin/console osmcha:new-mapper germany-berlin-neukoelln
    update-europe-germany-berlin:
        spec: '30 1 * * *'
        commands:
            start: php bin/console osmcha:new-mapper germany-berlin
    update-europe-germany-bremen:
        spec: '30 1 * * *'
        commands:
            start: php bin/console osmcha:new-mapper germany-bremen
    update-europe-germany:
        spec: '30 1 * * *'
        commands:
            start: php bin/console osmcha:new-mapper germany
    update-europe-hungary:
        spec: '30 1 * * *'
        commands:
            start: php bin/console osmcha:new-mapper hungary
    update-europe-ireland:
        spec: '30 1 * * *'
        commands:
            start: php bin/console osmcha:new-mapper ireland
    update-europe-italy:
        spec: '30 1 * * *'
        commands:
            start: php bin/console osmcha:new-mapper italy
    update-europe-kosovo:
        spec: '30 1 * * *'
        commands:
            start: php bin/console osmcha:new-mapper kosovo
    update-europe-luxembourg:
        spec: '30 1 * * *'
        commands:
            start: php bin/console osmcha:new-mapper luxembourg
    update-europe-montenegro:
        spec: '30 1 * * *'
        commands:
            start: php bin/console osmcha:new-mapper montenegro
    update-europe-poland:
        spec: '30 1 * * *'
        commands:
            start: php bin/console osmcha:new-mapper poland
    update-europe-portugal:
        spec: '30 1 * * *'
        commands:
            start: php bin/console osmcha:new-mapper portugal
    update-europe-romania:
        spec: '30 1 * * *'
        commands:
            start: php bin/console osmcha:new-mapper romania
    update-europe-scotland:
        spec: '30 1 * * *'
        commands:
            start: php bin/console osmcha:new-mapper scotland
    update-europe-serbia:
        spec: '30 1 * * *'
        commands:
            start: php bin/console osmcha:new-mapper serbia
    update-europe-slovenia:
        spec: '30 1 * * *'
        commands:
            start: php bin/console osmcha:new-mapper slovenia
    update-europe-spain:
        spec: '30 1 * * *'
        commands:
            start: php bin/console osmcha:new-mapper spain
    update-europe-switzerland:
        spec: '30 1 * * *'
        commands:
            start: php bin/console osmcha:new-mapper switzerland
    update-europe-ukraine:
        spec: '30 1 * * *'
        commands:
            start: php bin/console osmcha:new-mapper ukraine
    update-northamerica-ca-bc:
        spec: '0 9 * * *'
        commands:
            start: php bin/console osmcha:new-mapper ca-bc
    update-northamerica-ca-on:
        spec: '0 6 * * *'
        commands:
            start: php bin/console osmcha:new-mapper ca-on
    update-northamerica-california:
        spec: '0 9 * * *'
        commands:
            start: php bin/console osmcha:new-mapper california
    update-northamerica-guatemala:
        spec: '0 7 * * *'
        commands:
            start: php bin/console osmcha:new-mapper guatemala
    update-northamerica-kansas:
        spec: '0 7 * * *'
        commands:
            start: php bin/console osmcha:new-mapper kansas
    update-northamerica-massachusetts:
        spec: '0 6 * * *'
        commands:
            start: php bin/console osmcha:new-mapper massachusetts
    update-northamerica-michigan:
        spec: '0 6 * * *'
        commands:
            start: php bin/console osmcha:new-mapper michigan
    update-northamerica-newyork:
        spec: '0 6 * * *'
        commands:
            start: php bin/console osmcha:new-mapper newyork
    update-northamerica-ohio:
        spec: '0 6 * * *'
        commands:
            start: php bin/console osmcha:new-mapper ohio
    update-northamerica-oregon:
        spec: '0 9 * * *'
        commands:
            start: php bin/console osmcha:new-mapper oregon
    update-northamerica-panama:
        spec: '0 6 * * *'
        commands:
            start: php bin/console osmcha:new-mapper panama
    update-northamerica-texas:
        spec: '0 7 * * *'
        commands:
            start: php bin/console osmcha:new-mapper texas
    update-northamerica-utah:
        spec: '0 8 * * *'
        commands:
            start: php bin/console osmcha:new-mapper utah
    update-northamerica-vermont:
        spec: '0 6 * * *'
        commands:
            start: php bin/console osmcha:new-mapper vermont
    update-northamerica-washington:
        spec: '0 9 * * *'
        commands:
            start: php bin/console osmcha:new-mapper washington
    update-southamerica-bogota:
        spec: '0 6 * * *'
        commands:
            start: php bin/console osmcha:new-mapper bogota
    update-southamerica-bolivia:
        spec: '0 5 * * *'
        commands:
            start: php bin/console osmcha:new-mapper bolivia
    update-southamerica-brazil:
        spec: '30 4 * * *'
        commands:
            start: php bin/console osmcha:new-mapper brazil
    update-southamerica-chile:
        spec: '30 4 * * *'
        commands:
            start: php bin/console osmcha:new-mapper chile
    update-southamerica-colombia:
        spec: '0 6 * * *'
        commands:
            start: php bin/console osmcha:new-mapper colombia
